# Generated by Django 3.2 on 2021-05-07 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Kategoriya')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Women',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Matn')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Rasm')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_published', models.BooleanField(default=True, verbose_name='Publikatsiya')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='women.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Mashhur ayol',
                'verbose_name_plural': 'Mashhur ayollar',
                'ordering': ['-time_update'],
            },
        ),
    ]
