# Generated by Django 3.2 on 2021-04-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
